#!/usr/bin/env bash
# A script that transfers a file from our client to a server

#Check if the correct number of parameters are provided
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else

    # Get parameters
    file_path="$1"
    server_IP="$2"
    username="$3"
    SSH_key_path="$4"

    scp -o StrictHostKeyChecking=no -i SSH_key_path file_path username@server_IP:~/

fi
