#!/usr/bin/env bash
# A script that configures a new Ubuntu machine:
# Install nginx on your web-01 server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page),# using curl, it must return a page that contains the string Hello World!

(
# Check for package list updates and install nginx
sudo apt update
sudo apt -y install nginx

# Configure nginx
sudo mkdir -p /etc/nginx/sites-available


sudo bash -c 'echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    root /var/www/html;
    index index.html;
    location / {
        return 200 "Hello World!\n";
    }
}" > /etc/nginx/sites-available/default'

# Create a symbolic link to sites-enabled
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
sudo service nginx restart
sudo service enable nginx
)
