#!/usr/bin/env bash
# A script that configures a new Ubuntu machine:
# Install nginx on your web-01 server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page),# using curl, it must return a page that contains the string Hello World!


# Check for package list updates and install nginx
sudo apt-get update
sudo apt-get -y install nginx

# Configure nginx
# sudo bash -c 'echo "server {
#    listen 80;
#    listen [::]:80;
#    server_name _;
#    root /var/www/html;
#    index index.html;
#    location / {
#        return 200 \"Hello World!\n\";
#    }
#}" > /etc/nginx/sites-enabled/default'

echo 'Hello World' | sudo tee /var/www/html/index.html
sudo service nginx restart
