#!/usr/bin/env bash
# This is a script that pings an IP address passed as an argument 5times

if [ $# -ne 1 ]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
	exit 1
fi

ip_address="$1"

ping -c 5 "$ip_address"
