#!/usr/bin/env bash
# This is a Bash script that displays To infinity and beyond indefinitely, with conditions


handle_sigterm()
{
	echo "I am invincible!!!"
}


trap handle_sigterm SIGTERM
while (( 1 ))
do
	echo "To infinity and beyond"
	sleep 2
done
