#!/usr/bin/env bash
# This is a Bash script to display user information from a file

filename="/etc/passwd"

while IFS=: read -r username _ uid gid gecos home shell _; do
        echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode x, more info about the user here: $gecos"
done < "$filename"
