#!/usr/bin/env bash
# This is a Bash script to display the visitor IP along with the HTTP
# status code from the Apache log file.

log_file="apache-access.log"

grep 'HTTP/1\.[01]" [123].. ' "$log_file" | awk '{print $1, $9}'
