#!/usr/bin/env bash
# This is a  Bash script that displays Best School 10 times using while loop

i=1
while [ $i -le 10 ];
do
	echo "Best School"
	i=$((i+1))
# i increment can also be written as ((i++))
done
