#!/usr/bin/env bash
# This is a Bash script that displays Best School 10 times but with an
# additional message on the 9th iteration

i=1
while [ $i -le 10 ]
do
	echo "Best School"
	if [ $i -eq 9 ];
	then
		echo "Hi"
	fi
	((i++))
done
