#!/usr/bin/env bash
# This is a Bash script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed

items=$(ls)

for item in "${items[@]}"; do
	name=$(echo "$item" | cut -d'-' -f2-)
	echo "$name"
done

