#!/usr/bin/env bash
# A script that configures the Nginx container to the nginx user

chown nginx:nginx /etc/nginx/nginx.conf
chmod 777 /etc/nginx/nginx.conf
sed -i 's/8080/g' /etc/nginx/sites-available/default
sudo -u service nginx restart
