#!/usr/bin/env bash
# Configuring our SSH client

# Configure SSH to use specified private key
echo "IdentifyFile ~/.ssh/school" >> ~/.ssh/config

# Configure SSH client to refuse to authenticate using a password
sudo sed -i 's/PasswordAuthentication yes/PasswordAuthentication no/'\
/etc/ssh/sshd_config

#Restart SSH service to apply changes
sudo service ssh restart
